DOMAIN = "svt_light_controller"

CONF_CONTROLLERS = "controllers"
CONF_INPUT_LIGHTS = "input_lights"
CONF_UNIQUE_ID = "unique_id"
CONF_NAME = "name"
CONF_LIMITS = "limits"
CONF_BRIGHTNESS_MIN_PCT = "brightness_min_pct"
CONF_BRIGHTNESS_MAX_PCT = "brightness_max_pct"
CONF_CT_MIN_KELVIN = "ct_min_kelvin"
CONF_CT_MAX_KELVIN = "ct_max_kelvin"
CONF_WEATHER_MIN_KELVIN = "weather_min_kelvin"

SVTLC_PREFIX = "SVTLC"
CONFIG_PATH = "/config/svtlc_controllers.json"
